name: buildDocker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/be16app:latest 
      - 
        name: multiple command
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/be16app:latest
            docker run --name ${{ secrets.CNAME }} -d -p 8000:8000 --network="host" -e DBUser=${{ secrets.DBUSER }} -e DBHost=${{ secrets.DBHOST }} -e DBPort=${{ secrets.DBPORT }} -e DBName=${{ secrets.DBNAME }} -e JWT_SECRET=${{ secrets.JWT }} ${{ secrets.DOCKERHUB_USERNAME }}/be16app:latest